FROM node:22.3.0-alpine3.19
WORKDIR /usr/src/app

# Install system dependencies first
RUN npm install -g pnpm

# Install app dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy app source code
COPY . .

# Run the development server
CMD ["pnpm", "run", "dev"]

# Expose the port the app runs on
EXPOSE 3000