---
version: "3"

name: s3-file-manager
services:
  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/s3_file_manager
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_ID=test
      - AWS_ACCESS_SECRET=test
    volumes:
      - ../apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - LS_LOG=warn
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./localstack/ready.sh:/etc/localstack/init/ready.d/ready.sh"

    healthcheck:
      test: ["CMD", "awslocal", "s3api", "list-buckes"]
      interval: 1s
      timeout: 5s
      retries: 30

  postgres:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: s3_file_manager
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - 5432:5432

volumes:
  postgres:
