---
version: "3"

name: s3-file-manager
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - LS_LOG=warn
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./localstack/ready.sh:/etc/localstack/init/ready.d/ready.sh"

    healthcheck:
      test: ["CMD", "awslocal", "s3api", "list-buckes"]
      interval: 1s
      timeout: 5s
      retries: 30

  postgres:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: s3_file_manager
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 30
    ports:
      - 5432:5432

volumes:
  postgres:
